config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.views import index, contacts, category, products, product
from main.apps import MainConfig

app_name = MainConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('category/', category, name='category'),
    path('<int:pk>/products/', products, name='products'),
    path('<int:pk>/product/', product, name='product')
]

main/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    title = models.CharField(max_length=55, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    imagine = models.ImageField(upload_to='categorys/', verbose_name='Фотография', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    brand = models.CharField(max_length=100, verbose_name='Брэнд')
    description = models.TextField(verbose_name='Описание')
    imagine = models.ImageField(upload_to='books/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField()
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    last_modified_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    def __str__(self):
        return f"Название: {self.title}. Автор: {self.brand}. Описание: {self.description}. " \
               f"Цена: {self.price}."

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

main/views.py
from django.shortcuts import render
from main.models import Category, Product


def index(request):
    context = {
        'title': 'Главная'
    }
    return render(request, 'main/index.html', context)


def contacts(request):
    context = {
        'title': 'Контакты'
    }
    return render(request, 'main/contacts.html', context)


def category(request):
    context = {
        'objects_list': Category.objects.all(),
        'title': 'Категории товаров'
    }
    return render(request, 'main/category.html', context)


def products(request, pk):
    category_name = Category.objects.get(pk=pk)
    context = {
        'objects_list': Product.objects.filter(category=pk),
        'title': category_name
    }
    return render(request, 'main/products.html', context)


def product(request, pk):
    context = {
        'objects_list': Product.objects.get(pk=pk),
        'title': 'Товар'
    }
    return render(request, 'main/product.html', context)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-dark" style="background-color: #0000CF;" aria-label="First navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">Сантехника-онлайн</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01"
                aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample01">
            <ul class="navbar-nav me-auto mb-2">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'main:contacts' %}">Контакты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'main:category' %}">Категории</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
            <form role="search">
                <input class="form-control" type="search" placeholder="Search" aria-label="Search">
            </form>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <span class="mb-3 mb-md-0 text-body-secondary">&copy; {% now 'Y' %} Сантехника онлайн</span>
        </div>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

main/templates/main/category.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container py-5">
    <h1 style="text-align: center" class="text-body-emphasis">Выберите категорию</h1>
</div>
{% for object in objects_list %}
<div class="row">
    <div class="col-12 col-lg-10 offset-lg-1 m-auto">
        <div class="card mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col-3"><img src="{{ object.imagine|my_media }}" class="img-fluid" width="250"></div>
                    <div class="col-9">
                        <h2 class="h4">{{ object.title }}</h2>
                        <p>{{ object.description }}</p>
                        <a href="{% url 'main:products' object.pk %}" class="btn btn-outline-primary btn-sm mr-3 mb-2">Показать</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

main/templates/main/contacts.html
{% extends 'main/base.html' %}

{% block content %}
<div class="my-5">
    <div class="p-5 text-center bg-body-tertiary">
        <div class="container py-5">
            <h1 class="text-body-emphasis">Контакты</h1>
            <p class="col-lg-8 mx-auto lead">
                Номер: + 7 777 77 77<br>
                Почта: example@mail.ru<br>
                Адрес: г. Воронеж, Московский проспект, д. 13
            </p>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}

<div class="container my-5">
    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
            <h1 class="display-4 fw-bold lh-1 text-body-emphasis">Воплатим ваши фантазии в жизнь!</h1>
            <p class="lead">Добро пожаловать в интернет магазин «Сантехника онлайн». У нас Вы можете купить фирменную
                сантехнику по выгодным ценам с доставкой на дом, а также заказать услугу по ее установке.

                Купить сантехнику онлайн очень просто – положите товар в корзину и отправьте заказ и мы оперативно
                оформим и доставим ваш заказ по Москве, а также в любой другой город России!</p>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                <a href="{% url 'main:category' %}" style="background-color: #0000CF;" type="button"
                        class="btn btn-primary btn-lg px-4 me-md-2 fw-bold">Перейти в каталог
                </a>
            </div>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
            <img class="rounded-lg-3" src="{%static 'image/header.jpg' %}" width="450">
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/product.html
{% extends 'main/base.html' %}
{% load my_tags %}

{% block content %}
<main class="container mt-3">
    <div class="card my-4 mx-auto">
        <div class="card-body m-2 m-md-4">
            <article class="row">
                <div class="col-5"><img src="{{ objects_list.imagine|my_media }}" class="img-fluid" alt=""></div>
                <div class="col-7">
                    <section class="teacher=info">
                        <h1 class="h2">{{ objects_list.title }}</h1>
                        <p><span class="badge bg-dark">{{ objects_list.available|available_filter }}</span>
                            {{ objects_list.price }} ₽</p>
                        <p>{{ objects_list.description }}</p>
                    </section>

                    <section class="available">
                        <a href="#" class="btn btn-outline-success mr-2">Добавить в корзину</a>
                    </section>
                </div>
            </article>
        </div>
    </div>
</main>
{% endblock %}

main/templates/main/products.html
{% extends 'main/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container py-5">
    <h1 style="text-align: center" class="text-body-emphasis">{{ title }}</h1>
</div>
<main class="container mt-3">
    <div class="row mt-5">
        {% for object in objects_list %}
        <div class="col-4">
            <div class="card mb-4">
                <img src="{{ object.imagine|my_media }}" class="card-img-top" width="350" height="350">
                <div class="card-body">
                    <h2 class="h5 card-title">{{ object.title }}</h2>
                    <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'main:product' object.pk %}" class="btn btn-sm btn-primary">Подробнее</a>
                        <p class="float-right">{{ object.price }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}